/**
 * Predictive Analysis Subsystem Scoring Engine
 * Rule-based risk scoring for hydrated PMS patient data
 */

const DISCLAIMER =
  "This assessment is generated by an automated rule-based predictive analysis system for informational purposes only and does not replace professional medical diagnosis or treatment.";

const MEDICAL_HISTORY_POINTS = {
  cardiovascular: 20,
  metabolic: 18,
  respiratory: 15,
  renal: 15,
  mental: 12,
  cancer: 20,
};

const SPECIALIST_MAP = {
  cardiovascular: ["Cardiologist"],
  metabolic: ["Endocrinologist"],
  respiratory: ["Pulmonologist"],
  renal: ["Nephrologist"],
  mental: ["Psychiatrist", "Psychologist"],
  cancer: ["Oncologist"],
};

const LAB_TEST_MAP = {
  cardiovascular: ["ECG", "Lipid Profile", "Blood Pressure Monitoring"],
  metabolic: ["HbA1c", "Blood Glucose", "Insulin Test"],
  respiratory: ["Chest X-ray", "Pulmonary Function Test"],
  renal: ["Kidney Function Test", "Creatinine Test", "Urinalysis"],
  cancer: ["Complete Blood Count (CBC)", "Tumor Marker Screening", "Imaging"],
  mental: ["Comprehensive Metabolic Panel"],
};

const CONDITION_PATTERNS = {
  cardiovascular: /\b(hypertension|heart|cardio|stroke|arrhythmia|coronary|angina|myocardial|heart failure)\b/i,
  metabolic: /\b(diabetes|metabolic|glucose|insulin|obesity|hyperlipidemia|cholesterol)\b/i,
  respiratory: /\b(asthma|copd|respiratory|bronchitis|pneumonia|lung|upper respiratory)\b/i,
  renal: /\b(renal|kidney|nephro|ckd|dialysis)\b/i,
  mental: /\b(anxiety|depression|mental|psychiatric|bipolar|stress)\b/i,
  cancer: /\b(cancer|oncology|tumou?r|malignan)\b/i,
};

function cleanText(value) {
  if (value === null || value === undefined) return "";
  const text = String(value).trim();
  if (!text) return "";

  const normalized = text.toLowerCase();
  if (normalized === "n/a" || normalized === "undefined" || normalized === "null") {
    return "";
  }

  return text;
}

function toNumber(value) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : null;
}

function pushUnique(target, value) {
  const text = cleanText(value);
  if (!text) return;

  if (!target.some((item) => item.toLowerCase() === text.toLowerCase())) {
    target.push(text);
  }
}

function getRiskLevel(score) {
  if (score >= 70) return "Critical";
  if (score >= 45) return "High";
  if (score >= 20) return "Moderate";
  return "Low";
}

function formatConditionLabel(condition) {
  return cleanText(condition)
    .replace(/[_-]+/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function getAgePoints(age) {
  if (age >= 65) return 18;
  if (age >= 50) return 12;
  if (age >= 40) return 8;
  return 0;
}

function normalizeDiet(diet) {
  const label = cleanText(diet);
  const normalized = label.toLowerCase();

  if (!normalized) {
    return { label: "", category: "" };
  }

  if (
    normalized.includes("poor") ||
    normalized.includes("high sodium") ||
    normalized.includes("processed") ||
    normalized.includes("fried") ||
    normalized.includes("high sugar") ||
    normalized.includes("unhealthy")
  ) {
    return { label, category: "poor" };
  }

  if (
    normalized.includes("balanced") ||
    normalized.includes("healthy") ||
    normalized.includes("mediterranean")
  ) {
    return { label, category: "balanced" };
  }

  return { label, category: "average" };
}

function normalizePhysicalActivity(activity) {
  const label = cleanText(activity);
  const normalized = label.toLowerCase();

  if (!normalized) {
    return { label: "", category: "" };
  }

  if (
    normalized.includes("sedentary") ||
    normalized.includes("inactive") ||
    normalized.includes("no exercise")
  ) {
    return { label, category: "sedentary" };
  }

  if (normalized.includes("light")) {
    return { label, category: "light" };
  }

  if (normalized.includes("moderate")) {
    return { label, category: "moderate" };
  }

  if (normalized.includes("active")) {
    return { label, category: "active" };
  }

  return { label, category: "light" };
}

function normalizeLifestyle(lifestyle = {}) {
  return {
    smoking: Boolean(lifestyle?.smoking),
    alcohol: Boolean(lifestyle?.alcohol),
    diet: normalizeDiet(lifestyle?.diet),
    physicalActivity: normalizePhysicalActivity(lifestyle?.physical_activity || lifestyle?.physicalActivity),
  };
}

function addContribution(target, label, category, points) {
  if (!points || points <= 0) return;
  target.push({
    label,
    category,
    points,
  });
}

function getLifestylePoints(lifestyle = {}) {
  const normalized = normalizeLifestyle(lifestyle);
  const contributions = [];

  if (normalized.smoking) {
    addContribution(contributions, "Smoking", "Lifestyle", 15);
  }

  if (normalized.alcohol) {
    addContribution(contributions, "Alcohol use", "Lifestyle", 12);
  }

  if (normalized.diet.category === "poor") {
    addContribution(
      contributions,
      normalized.diet.label || "Poor diet",
      "Lifestyle",
      10
    );
  }

  if (normalized.physicalActivity.category === "sedentary") {
    addContribution(
      contributions,
      normalized.physicalActivity.label || "Sedentary lifestyle",
      "Lifestyle",
      10
    );
  } else if (normalized.physicalActivity.category === "light") {
    addContribution(
      contributions,
      normalized.physicalActivity.label || "Light physical activity",
      "Lifestyle",
      4
    );
  }

  return {
    normalized,
    contributions,
  };
}

function normalizeConditions(conditions = []) {
  const conditionKeys = [];

  conditions.forEach((condition) => {
    const normalized = cleanText(condition).toLowerCase().replace(/[_-]+/g, " ");
    if (!normalized) return;

    if (MEDICAL_HISTORY_POINTS[normalized]) {
      pushUnique(conditionKeys, normalized);
      return;
    }

    Object.entries(CONDITION_PATTERNS).forEach(([key, pattern]) => {
      if (pattern.test(normalized)) {
        pushUnique(conditionKeys, key);
      }
    });
  });

  return conditionKeys;
}

function parseBloodPressure(value) {
  const text = cleanText(value);
  if (!text.includes("/")) return { systolic: null, diastolic: null };

  const [systolic, diastolic] = text.split("/").map((part) => toNumber(part));
  return { systolic, diastolic };
}

function getVitalsContributions(vitals = {}) {
  const contributions = [];
  const { systolic, diastolic } = parseBloodPressure(vitals?.blood_pressure);

  if ((systolic && systolic >= 140) || (diastolic && diastolic >= 90)) {
    addContribution(contributions, "Elevated blood pressure", "Vitals", 8);
  } else if ((systolic && systolic >= 130) || (diastolic && diastolic >= 85)) {
    addContribution(contributions, "Borderline blood pressure", "Vitals", 4);
  }

  const heartRate = toNumber(vitals?.heart_rate);
  if (heartRate && (heartRate > 100 || heartRate < 50)) {
    addContribution(contributions, "Abnormal heart rate", "Vitals", 3);
  }

  const temperature = toNumber(vitals?.temperature);
  if (temperature && temperature >= 100.4) {
    addContribution(contributions, "Elevated temperature", "Vitals", 2);
  }

  return contributions;
}

function getRecommendations({ lifestyle, conditionKeys, riskLevel, vitals }) {
  const recommendations = [];
  const seen = new Set();

  const add = (value) => {
    const text = cleanText(value);
    if (!text || seen.has(text)) return;
    seen.add(text);
    recommendations.push(text);
  };

  if (lifestyle.smoking) {
    add("Stop smoking or reduce to zero cigarettes per day");
    add("Consider nicotine replacement therapy or support programs");
    add("Avoid secondhand smoke exposure");
  }

  if (lifestyle.alcohol) {
    add("Reduce alcohol consumption to safe limits");
    add("Seek professional support if alcohol reduction is difficult");
  }

  if (lifestyle.diet.category === "poor") {
    add("Reduce sodium intake to less than 2,300mg per day");
    add("Increase fruits, vegetables, and whole grains");
    add("Avoid processed and fried foods");
  }

  if (lifestyle.physicalActivity.category === "sedentary") {
    add("Aim for 150 minutes of moderate aerobic activity per week");
    add("Break up prolonged sitting with movement every hour");
  } else if (lifestyle.physicalActivity.category === "light") {
    add("Increase weekly exercise intensity gradually");
  }

  conditionKeys.forEach((condition) => {
    if (condition === "cardiovascular") {
      add("Monitor blood pressure regularly");
      add("Reduce salt intake");
      add("Schedule cardiovascular follow-up");
    }

    if (condition === "metabolic") {
      add("Monitor blood glucose levels regularly");
      add("Maintain consistent meal timing");
      add("Work with a dietitian on meal planning");
    }

    if (condition === "respiratory") {
      add("Avoid air pollutants and known respiratory triggers");
      add("Monitor for shortness of breath or worsening cough");
    }

    if (condition === "renal") {
      add("Monitor kidney function regularly");
      add("Maintain hydration and review sodium intake");
    }

    if (condition === "mental") {
      add("Seek mental health support or counseling");
      add("Practice sleep and stress management routines");
    }

    if (condition === "cancer") {
      add("Coordinate follow-up imaging and oncology review");
    }
  });

  const { systolic, diastolic } = parseBloodPressure(vitals?.blood_pressure);
  if ((systolic && systolic >= 130) || (diastolic && diastolic >= 85)) {
    add("Track blood pressure at home and review trends with a clinician");
  }

  if (riskLevel === "High" || riskLevel === "Critical") {
    add("Schedule a comprehensive health assessment promptly");
    add("Review this result with a licensed clinician before changing treatment");
  }

  add("Schedule regular preventive health checkups");
  add("Stay hydrated and maintain a healthy sleep schedule");

  while ((riskLevel === "High" || riskLevel === "Critical") && recommendations.length < 5) {
    add("Continue regular health monitoring and follow-up care");
  }

  return recommendations.slice(0, 10);
}

function getSpecialists({ conditionKeys, riskLevel, vitals }) {
  const specialists = new Set();

  conditionKeys.forEach((condition) => {
    (SPECIALIST_MAP[condition] || []).forEach((value) => specialists.add(value));
  });

  const { systolic, diastolic } = parseBloodPressure(vitals?.blood_pressure);
  if ((systolic && systolic >= 140) || (diastolic && diastolic >= 90)) {
    specialists.add("Cardiologist");
  }

  if ((riskLevel === "High" || riskLevel === "Critical") && specialists.size === 0) {
    specialists.add("Internal Medicine");
    specialists.add("Preventive Medicine");
  }

  return Array.from(specialists);
}

function getLabTests({ conditionKeys, riskLevel, vitals }) {
  const tests = new Set();

  conditionKeys.forEach((condition) => {
    (LAB_TEST_MAP[condition] || []).forEach((value) => tests.add(value));
  });

  const { systolic, diastolic } = parseBloodPressure(vitals?.blood_pressure);
  if ((systolic && systolic >= 130) || (diastolic && diastolic >= 85)) {
    tests.add("Blood Pressure Monitoring");
    tests.add("ECG");
  }

  if (riskLevel === "High" || riskLevel === "Critical") {
    tests.add("Comprehensive Metabolic Panel");
    tests.add("Complete Blood Count (CBC)");
    tests.add("Lipid Profile");
  }

  return Array.from(tests);
}

function breakdownArrayToObject(breakdown = []) {
  return breakdown.reduce((acc, item) => {
    const label = cleanText(item?.label);
    const points = Number(item?.points) || 0;
    if (!label || points <= 0) return acc;
    acc[label] = (acc[label] || 0) + points;
    return acc;
  }, {});
}

function scorePatient(data = {}) {
  const patientId = cleanText(data?.patient_id || data?.patientId) || null;
  const age = Number(data?.age) || 0;
  const lifestyle = data?.lifestyle || {};
  const vitals = data?.vitals || {};
  const rawConditions = Array.isArray(data?.condition_categories) && data.condition_categories.length > 0
    ? data.condition_categories
    : Array.isArray(data?.patient_record)
    ? data.patient_record
    : [];

  const breakdown = [];

  addContribution(breakdown, "Age", "Demographics", getAgePoints(age));

  const lifestyleResult = getLifestylePoints(lifestyle);
  breakdown.push(...lifestyleResult.contributions);

  const conditionKeys = normalizeConditions(rawConditions);
  conditionKeys.forEach((condition) => {
    addContribution(
      breakdown,
      `${formatConditionLabel(condition)} history`,
      "Medical History",
      MEDICAL_HISTORY_POINTS[condition] || 0
    );
  });

  breakdown.push(...getVitalsContributions(vitals));

  const score = Math.min(
    breakdown.reduce((sum, item) => sum + (Number(item?.points) || 0), 0),
    100
  );

  const riskLevel = getRiskLevel(score);
  const recommendations = getRecommendations({
    lifestyle: lifestyleResult.normalized,
    conditionKeys,
    riskLevel,
    vitals,
  });
  const specialists = getSpecialists({
    conditionKeys,
    riskLevel,
    vitals,
  });
  const labTests = getLabTests({
    conditionKeys,
    riskLevel,
    vitals,
  });

  return {
    patient_id: patientId,
    riskScore: score,
    risk_score: score,
    risk_level: riskLevel,
    recommendations,
    suggested_specialist: specialists,
    specialists,
    optional_lab_tests: labTests,
    lab_tests: labTests,
    breakdown,
    score_breakdown: breakdownArrayToObject(breakdown),
    disclaimer: DISCLAIMER,
  };
}

module.exports = { scorePatient, DISCLAIMER };
